### ISSUE TITLE
After place a Rechiseled mod block using Bank game crashes and after restart Bank item disappears

### ISSUE THREAD

**Issue by DanielRibas1** [Natanaelel/BankStorage#32]
**Mod version**
1.4.2+1.21

**Describe the bug**
Using Craftoria Modpack version 1.5.0 in a Survival game.
When placing a [Rechiseled Mod](https://www.curseforge.com/minecraft/mc-mods/rechiseled) block using Bank at any level.
After that the game crashes and after I restart the game the Bank item with its contents is gone.
If I use a Bank Link only the Bank Link is gone.

**To Reproduce**
1. Select Bank item in the hotbar
2. Switch with Shift-Right Click for the Rechiseled mod block inside the inventory of the Bank.
3. Place a Rechiseled mod block anywhere.
4. Game crashes.
5. Restart the save game.
6. Missing Bank item in the player inventory.

**Expected behavior**
Place the block with Bank without a crash, and if so the Bank item to not disappear in my inventory.

**Screenshots**

**Logs**
---- Minecraft Network Protocol Error Report ----
// All lines are down!

Time: 2024-10-28 12:44:06
Description: Packet handling error

io.netty.handler.codec.EncoderException: Failed to encode packet 'serverbound/minecraft:custom_payload'
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.IdDispatchCodec.encode(IdDispatchCodec.java:55) ~[client-1.21.1-20240808.144430-srg.jar%23497!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.IdDispatchCodec.encode(IdDispatchCodec.java:14) ~[client-1.21.1-20240808.144430-srg.jar%23497!/:?] {re:classloading}
	at TRANSFORMER/neoforge@21.1.66/net.neoforged.neoforge.network.filters.GenericPacketSplitter.encode(GenericPacketSplitter.java:104) ~[neoforge-21.1.66-universal.jar%23498!/:?] {re:classloading}
	at TRANSFORMER/neoforge@21.1.66/net.neoforged.neoforge.network.filters.GenericPacketSplitter.encode(GenericPacketSplitter.java:39) ~[neoforge-21.1.66-universal.jar%23498!/:?] {re:classloading}
	at MC-BOOTSTRAP/io.netty.codec@4.1.97.Final/io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90) ~[netty-codec-4.1.97.Final.jar%23130!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar%23136!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar%23136!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar%23136!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar%23136!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.ChannelOutboundHandlerAdapter.write(ChannelOutboundHandlerAdapter.java:113) ~[netty-transport-4.1.97.Final.jar%23136!/:4.1.97.Final] {re:computing_frames,re:mixin}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.Connection$2.write(Connection.java:528) ~[client-1.21.1-20240808.144430-srg.jar%23497!/:?] {re:classloading}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar%23136!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940) ~[netty-transport-4.1.97.Final.jar%23136!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966) ~[netty-transport-4.1.97.Final.jar%23136!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934) ~[netty-transport-4.1.97.Final.jar%23136!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:984) ~[netty-transport-4.1.97.Final.jar%23136!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[netty-transport-4.1.97.Final.jar%23136!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[netty-transport-4.1.97.Final.jar%23136!/:4.1.97.Final] {}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.Connection.doSendPacket(Connection.java:364) ~[client-1.21.1-20240808.144430-srg.jar%23497!/:?] {re:mixin,re:classloading,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.Connection.lambda$sendPacket$12(Connection.java:359) ~[client-1.21.1-20240808.144430-srg.jar%23497!/:?] {re:mixin,re:classloading,pl:mixin:A}
	at MC-BOOTSTRAP/io.netty.common@4.1.97.Final/io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar%23131!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) ~[netty-transport-4.1.97.Final.jar%23136!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.common@4.1.97.Final/io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar%23131!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.common@4.1.97.Final/io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar%23131!/:4.1.97.Final] {}
	at java.base/java.lang.Thread.run(Unknown Source) [?:?] {re:mixin}
Caused by: java.lang.RuntimeException: Failed encoding custom payload bankstorage:requestbank_c2s: java.lang.NullPointerException: Cannot invoke "java.util.UUID.getMostSignificantBits()" because "p_319838_" is null
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.protocol.common.custom.CustomPacketPayload$1.writeCap(CustomPacketPayload.java:42) ~[client-1.21.1-20240808.144430-srg.jar%23497!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.protocol.common.custom.CustomPacketPayload$1.encode(CustomPacketPayload.java:47) ~[client-1.21.1-20240808.144430-srg.jar%23497!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.protocol.common.custom.CustomPacketPayload$1.encode(CustomPacketPayload.java:29) ~[client-1.21.1-20240808.144430-srg.jar%23497!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.StreamCodec$4.encode(StreamCodec.java:81) ~[client-1.21.1-20240808.144430-srg.jar%23497!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.StreamCodec$5.encode(StreamCodec.java:97) ~[client-1.21.1-20240808.144430-srg.jar%23497!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.StreamCodec$5.encode(StreamCodec.java:87) ~[client-1.21.1-20240808.144430-srg.jar%23497!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.IdDispatchCodec.encode(IdDispatchCodec.java:53) ~[client-1.21.1-20240808.144430-srg.jar%23497!/:?] {re:classloading}
	... 24 more
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.UUID.getMostSignificantBits()" because "p_319838_" is null
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.FriendlyByteBuf.writeUUID(FriendlyByteBuf.java:480) ~[client-1.21.1-20240808.144430-srg.jar%23497!/:?] {re:mixin,re:classloading,pl:mixin:APP:packetfixer-common.mixins.json:FriendlyByteBufMixin from mod packetfixer,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.core.UUIDUtil$1.encode(UUIDUtil.java:71) ~[client-1.21.1-20240808.144430-srg.jar%23497!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.core.UUIDUtil$1.encode(UUIDUtil.java:63) ~[client-1.21.1-20240808.144430-srg.jar%23497!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.StreamCodec$8.encode(StreamCodec.java:156) ~[client-1.21.1-20240808.144430-srg.jar%23497!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.protocol.common.custom.CustomPacketPayload$1.writeCap(CustomPacketPayload.java:40) ~[client-1.21.1-20240808.144430-srg.jar%23497!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.protocol.common.custom.CustomPacketPayload$1.encode(CustomPacketPayload.java:47) ~[client-1.21.1-20240808.144430-srg.jar%23497!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.protocol.common.custom.CustomPacketPayload$1.encode(CustomPacketPayload.java:29) ~[client-1.21.1-20240808.144430-srg.jar%23497!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.StreamCodec$4.encode(StreamCodec.java:81) ~[client-1.21.1-20240808.144430-srg.jar%23497!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.StreamCodec$5.encode(StreamCodec.java:97) ~[client-1.21.1-20240808.144430-srg.jar%23497!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.StreamCodec$5.encode(StreamCodec.java:87) ~[client-1.21.1-20240808.144430-srg.jar%23497!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.IdDispatchCodec.encode(IdDispatchCodec.java:53) ~[client-1.21.1-20240808.144430-srg.jar%23497!/:?] {re:classloading}
	... 24 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Netty Local Client IO #0
Stacktrace:
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.PacketListener.fillCrashReport(PacketListener.java:33) ~[client-1.21.1-20240808.144430-srg.jar%23497!/:?] {re:classloading,re:mixin}
-- Connection --
Details:
	Protocol: play
	Flow: CLIENTBOUND
	Server type: <none>
	Server brand: neoforge
Stacktrace:
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.PacketListener.fillCrashReport(PacketListener.java:33) ~[client-1.21.1-20240808.144430-srg.jar%23497!/:?] {re:classloading,re:mixin}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.protocol.PacketUtils.fillCrashReport(PacketUtils.java:62) ~[client-1.21.1-20240808.144430-srg.jar%23497!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.multiplayer.ClientCommonPacketListenerImpl.storeDisconnectionReport(ClientCommonPacketListenerImpl.java:130) ~[client-1.21.1-20240808.144430-srg.jar%23497!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.multiplayer.ClientCommonPacketListenerImpl.createDisconnectionInfo(ClientCommonPacketListenerImpl.java:123) ~[client-1.21.1-20240808.144430-srg.jar%23497!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.Connection.exceptionCaught(Connection.java:157) ~[client-1.21.1-20240808.144430-srg.jar%23497!/:?] {re:mixin,re:classloading,pl:mixin:A}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:346) ~[netty-transport-4.1.97.Final.jar%23136!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:325) ~[netty-transport-4.1.97.Final.jar%23136!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:317) ~[netty-transport-4.1.97.Final.jar%23136!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.DefaultChannelPipeline$HeadContext.exceptionCaught(DefaultChannelPipeline.java:1377) ~[netty-transport-4.1.97.Final.jar%23136!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:346) ~[netty-transport-4.1.97.Final.jar%23136!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:325) ~[netty-transport-4.1.97.Final.jar%23136!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.DefaultChannelPipeline.fireExceptionCaught(DefaultChannelPipeline.java:907) ~[netty-transport-4.1.97.Final.jar%23136!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.ChannelFutureListener$3.operationComplete(ChannelFutureListener.java:69) ~[netty-transport-4.1.97.Final.jar%23136!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.ChannelFutureListener$3.operationComplete(ChannelFutureListener.java:65) ~[netty-transport-4.1.97.Final.jar%23136!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.common@4.1.97.Final/io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590) ~[netty-common-4.1.97.Final.jar%23131!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.common@4.1.97.Final/io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:557) ~[netty-common-4.1.97.Final.jar%23131!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.common@4.1.97.Final/io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492) ~[netty-common-4.1.97.Final.jar%23131!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.common@4.1.97.Final/io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:185) ~[netty-common-4.1.97.Final.jar%23131!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:95) ~[netty-transport-4.1.97.Final.jar%23136!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:30) ~[netty-transport-4.1.97.Final.jar%23136!/:4.1.97.Final] {}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.Connection.doSendPacket(Connection.java:379) ~[client-1.21.1-20240808.144430-srg.jar%23497!/:?] {re:mixin,re:classloading,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.Connection.lambda$sendPacket$12(Connection.java:359) ~[client-1.21.1-20240808.144430-srg.jar%23497!/:?] {re:mixin,re:classloading,pl:mixin:A}
	at MC-BOOTSTRAP/io.netty.common@4.1.97.Final/io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar%23131!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) ~[netty-transport-4.1.97.Final.jar%23136!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.common@4.1.97.Final/io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar%23131!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.common@4.1.97.Final/io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar%23131!/:4.1.97.Final] {}
	at java.base/java.lang.Thread.run(Unknown Source) [?:?] {re:mixin}

**Additional context**
I tried to replicate in a Test Creative world but without success, maybe the amount of blocks inside the Bank affects?

**Comment by Natanaelel** [comment]
Can you do /kubejs hand while holding the bank

**Comment by DanielRibas1** [comment]
The problem is that since the bug make the Bank disappear, and I cannot find the backup in this modpack with the launcher I use. :(

**Comment by DanielRibas1** [comment]
I have it again and I managed to call the /kubejs hand, because if I use the Bank Link what disappear is the Bank Link instead of the Real so I can get the data:

---
Real Bank 7 /kubejs hand
```
'bankstorage:bank_7[bankstorage:uuid=[I;-1660973785,-1481684910,-1119496122,-2127517618].bankstorage:type="bank_7".bankstorage:options={build:2b,pickup:0b,sort:0b}]'
- '#minecraft:dyeable'
- '#bankstorage:banks'
- '#modern_industrialization:replicator_blacklist'
- '@bankstorage'
```
---
Link Bank /kubejs hand
```
Item in hand:
'bankstorage:bank_link[bankstorage:uuid=[I;-1660973785,-1481684910,-1119496122,-2127517618]bankstorage:type="bank_7"; bankstorage:options=(build:2b,pickup:0b,sort:0b)]'
- '#minecraft:dyeable'
- '#bankstorage:banks'
- '@bankstorage'
```

**Comment by DanielRibas1** [comment]
I found that the crash is when I place block of the mod https://www.curseforge.com/minecraft/mc-mods/rechiseled, I will update the title and description

**Comment by Natanaelel** [comment]
Fixed in other mod
